apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

namePrefix: dev-

images:
  - name: productive-cloud-native-devex
    newName: lreimer/productive-cloud-native-devex

resources:
  # you can also specify a Git repo URL here
  - ../../base/
  - hoverfly-deployment.yaml
  - hoverfly-service.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hello World DEV.
      - PORT=8080
